language: java
jdk:
  - openjdk11

branches:
  only:
    - main

before_install:
  - cd ./foobar/
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build --exclude-task test"

before_deploy:
  - zip -r foobar *
  - cd ..
  - mkdir -p deploy
  - mv ./foobar/foobar.zip ./deploy/foobar.zip

deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY
    secret_access_key: $SECRET_KEY
    bucket: foobars3
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $ACCESS_KEY
    secret_access_key: $SECRET_KEY
    bucket: foobars3
    key: foobar.zip
    bundle_type: zip
    application: foobardeploy
    deployment_group: foobardeploygroup
    region: ap-northeast-2 
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - eikhyeon8542@gmail.com