language: java
jdk:
  - openjdk11

branches:
  only:
    - main

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: 
  - pwd
  - cd foobar/
  - "./gradlew clean build"

notifications:
  email:
    recipients:
      - eikhyeon8542@gmail.com