language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - cd ./foobar/
  - chmod +x gradlew

#Travis CI server home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"